#!/usr/bin/env node
// Regenerates src/server/version.ts from package.json's version field.
// Runs before every build/publish so the McpServer version string never
// drifts, without a runtime createRequire()/fs read (unsafe on Workers).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(scriptDir, "..", "package.json");
const outPath = join(scriptDir, "..", "src", "server", "version.ts");

const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));

const contents = `// Auto-generated by scripts/generate-version.mjs from package.json — do not edit by hand.
export const CELINA_MCP_VERSION = ${JSON.stringify(pkg.version)};
`;

writeFileSync(outPath, contents);
console.log(`Wrote ${outPath} (CELINA_MCP_VERSION = ${JSON.stringify(pkg.version)})`);
